neos_kariyer/ads/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "ads"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addads/',views.addads,name = "add_ads"),
    path('adsupdate/<int:id>',views.updateads,name = "ads_update"),
    path('adsdelete/<int:id>',views.ads_delete,name = "ads_delete"),
    path('views/<int:id>',views.ads_views_offer,name = "ads_views_offer"),
]

neos_kariyer/neos_kariyer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from home.views import *
from all_category.views import mail_gonderme
urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include("user_operations.urls")),
    path('',home_index,name="index"),
    path('ads/',include("ads.urls")),
    path('profile/',include("profil.urls")),
    path('views/',include("offer.urls")),
    #path('buy/',include("pay.urls")),
    path('mail/',mail_gonderme,name = "mail"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

neos_kariyer/user_operations/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user_operations"

urlpatterns = [
    path('register/',views.user_register,name = "register"),
    path('login/',views.user_login,name = "login"),
    path('logout/',views.user_logout,name = "logout"),
    path('reset/<int:idim>/<int:kod>',views.parola_sifirlama,name = "reset"),
    path('passrest/',views.pass_reset,name="passreset"),
    path('kod/',views.email_gonder,name = "email_gonder"),
    path('membership/<int:id>',views.membership,name = "membership"),

]

neos_kariyer/user_operations/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# kullanıcıların şirketmi yoksa freelancermi olduğunu belirler.
class user_status(models.Model):
    user = models.OneToOneField(User,null=True,on_delete = models.CASCADE,verbose_name="Kullanıcı Durumu")
    durum = models.BooleanField(null=True)

class parola_sifirla(models.Model):
    user = models.OneToOneField(User,null=True,on_delete = models.CASCADE,verbose_name="Kullanıcı Durumu")
    sifirla = models.IntegerField()

neos_kariyer/user_operations/forms.py
from django import forms
from django.forms import widgets

class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanıcı Adı" , widget=forms.TextInput(attrs={'placeholder': 'Kullanıcı Adı', 'class': 'form-control'}))
    password = forms.CharField(label = "Parola",widget = forms.PasswordInput(attrs={'placeholder': 'Parola', 'class': 'form-control'}))


class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50,label = "Kullanıcı Adı",widget=forms.TextInput(attrs={'class': "form-control", 
                'style': 'max-width: 600px;',
                'placeholder': 'Kullanıcı Adı'}))
    email = forms.EmailField(max_length=100,label = "Email",widget=forms.EmailInput(attrs={'class': "form-control", 
                'style': 'max-width: 600px;',
                'placeholder': 'E-Posta'}))
    password = forms.CharField(max_length=20,label = "Parola",widget = forms.PasswordInput(attrs={'class': "form-control", 
                'style': 'max-width: 600px;',
                'placeholder': 'Parola'}))
    confirm = forms.CharField(max_length=20,label ="Parolayı Doğrula",widget = forms.PasswordInput(attrs={'class': "form-control", 
                'style': 'max-width: 600px;',
                'placeholder': 'Parola Doğrula'}))
    
    def clean(self):
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm and len(password)<6:
            raise forms.ValidationError("Parola Hatalı")

        values = {
            "username" : username,
            "password" : password,
            "email"  : email
        }
        return values



class passreset(forms.Form):
    password = forms.CharField(max_length=20,label = "Parola",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="Parolayı Doğrula",widget = forms.PasswordInput)
    
    def clean(self):
        
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar Eşleşmiyor")

        values = {
            
            "password" : password
        }
        return values

neos_kariyer/user_operations/views.py
from django.shortcuts import render ,HttpResponse
from django.utils.datastructures import MultiValueDictKeyError
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from .models import *

# Create your views here.
#Kullanıcı Giriş Bölümü
def user_login(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            #messages.info(request,"Kullanıcı Adı veya Parola Hatalı")
            return render(request,"user_operations_temp/login.html",context)

        messages.success(request,"Başarıyla Giriş Yaptınız")
        login(request,user)
        #return redirect("index")
    return render(request, "user_operations_temp/login.html",context)
#Kullanını Kayıt Sayfasıdır.
def user_register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        newUser = User(username =username,email=email)
        newUser.set_password(password)
        try:
            newUser.save()
            login(request,newUser)
            messages.info(request,"Başarıyla Kayıt Oldunuz...")
            return redirect("/user/membership/3")
        except:
            messages.info(request,"İstediğiniz Kullanıcı Adı Kullanılmaktadır...")
            return redirect("/user/register/")
        
    context = {
            "form" : form
        }
    return render(request,"user_operations_temp/register.html",context)
def user_logout(request):
    logout(request)
    messages.success(request,"Başarıyla Çıkış Yaptınız")
    return redirect("index")
#Kullanıcı Druumlarını Düzenliyip Obje Oluşturulan Yerdir Bağlanti Models.py dir
def membership(request,id):
    if id == 3:
        print("Selamlar")
    elif id == 1:
        z  = user_status.objects.create(durum = 1)
        z.user = request.user
        z.save()
        return redirect("/profile/profil/")
    elif id == 0:
        z  = user_status.objects.create(durum = 0)
        z.user = request.user
        z.save()
        return redirect("/profile/company/")
    return render(request, "user_operations_temp/membership.html")
import random
from django.core.mail import send_mail
def email_gonder(request):
    print("Selam")
    username = request.POST.get('dili')
    mail_alindi = 0
    for i in username:
        if i == "@":
            mail_alindi = 1
            break
    if mail_alindi == 1:
        m = User.objects.filter(email=username)
        for i in m :
            idim = i.id
            mail = i.email
        try:
            ker = parola_sifirla.objects.filter(user_id = idim)
            
            print(ker)
        except:
            ker = 0
        if ker:
            gonder = random.randint(111111, 999999)
            print(gonder)
            parola_sifirla.objects.filter(user_id=idim).update(sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        else:
            gonder = random.randint(111111, 999999)
            parola_sifirla.objects.create(user_id=idim,sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        return redirect("/user/reset/")
    else:
        m = User.objects.filter(username=username)
        for i in m :
            idim = i.id
            mail = i.email
        try:
            ker = parola_sifirla.objects.filter(user_id = idim)
            
            print(ker)
        except:
            ker = 0
        if ker:
            gonder = random.randint(111111, 999999)
            print(gonder)
            parola_sifirla.objects.filter(user_id=idim).update(sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        else:
            gonder = random.randint(111111, 999999)
            parola_sifirla.objects.create(user_id=idim,sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        return redirect("/user/passrest/")
from .forms import passreset
def parola_sifirlama(request,idim,kod):
    form = passreset(request.POST or None)
    if form.is_valid():
        password = form.cleaned_data.get("password")
        user = User.objects.get(id=idim)
        print(idim)
        if parola_sifirla.objects.filter(user_id = idim,sifirla=kod):
            user.set_password(password)
            user.save()
            messages.success(request, "Parola Sıfırlandı")
            return redirect("/user/login/")
        else:
            messages.success(request, "Kullanıcı Bulunamadı")
            return redirect("/user/reset/")
    return render(request, "user_operations_temp/password_reset.html",{"form":form})

def pass_reset(request):
    if request.POST:
        users = request.POST.get("bilgi")
        print(users)
        kod = request.POST.get("dogrulaemail")
        print(kod)
        mail_alma = 0

        if users and kod :
            print("if 1")
            for i in users:
                if i == "@":
                    mail_alma = 1
                    print("if 2")
                    break
            if mail_alma:
                print("if 3")
                m = User.objects.filter(email=users)
                for i in m:
                    idim = i.id
                user = User.objects.get(id=idim)
                if parola_sifirla.objects.filter(user_id = idim,sifirla=kod):
                    print("kod Doğru",kod)
                    return redirect("/user/reset/"+str(idim)+"/"+str(kod))
                    
            else:
                print("if 3")
                m = User.objects.filter(username=users)
                for i in m:
                    idim = i.id
                user = User.objects.get(id=idim)
                if parola_sifirla.objects.filter(user_id = idim,sifirla=kod):
                    print("kod Doğru",kod)
                    return redirect("/user/reset/"+str(idim)+"/"+str(kod))
        else:   
            print("else 1")
    return render(request, "user_operations_temp/first_pass_reset.html")

neos_kariyer/user_operations/templates/ads_temp/dashboard.html
{% extends "homebase.html" %}

{% block slider %}
<!--content-->
<div class="container-lg">

    <div class="row">

        <div class="col-12">
            <!--sıralama-->
            <div class="row">
                <div class="col">
                    <select class="form-select  form-select" id="kategori">
                        <option selected>Hepsi</option>
                        <option value="1">Yalnızca aktif ilanlarım</option>
                        <option value="2">Yalnızca kapalı ilanlarım</option>
                    </select>
                </div>
                <div class="col">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="neos yazılım" aria-label="ara"
                            aria-describedby="button-addon2">
                        <button class="btn btn-outline-secondary" type="button" id="button-addon2">Ara</button>
                    </div>
                </div>
            </div>
            <!--**sıralama**-->
            <h5>Oluşturduğunuz ilanlar</h5>
            <hr>
            <a class = "btn btn-success" href = "{% url 'ads:add_ads' %}">İlan Ekle </a>
            <hr>
            {% if articles %}
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Başlık</th>
                        <th scope="col">Teklif sayısı</th>
                        <th scope="col">En düşük teklif</th>
                        <th scope="col">Kalan süre</th>
                        <th scope="col">Yayın tarihi</th>
                        <th scope="col">Güncelle</th>
                        <th scope="col">Sil</th>

                    </tr>
                </thead>
                <tbody>
                    
                    {% for article in articles %}
                    <tr class="table-success" onclick="window.location='/ads/views/{{article.id}}';">
                        <th scope="row">{{article.ilan_basligi}}</th>
                        <td>{{article.offer_much}}</td>
                        <td>{{article.chip_amunt}}₺/ay</td>
                        <td>{{article.ilan_olusturma_tarihi}}</td>
                        <td>{{article.ilan_gecis_tablosu}}</td>
                        <td><a href="{% url 'ads:ads_update' article.id %}" class = "btn btn-danger">Güncelle</a></td>
                        <td><a href="{% url 'ads:ads_delete' article.id %}" class = "btn btn-danger">Sil</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% else %}
<div class = "alert alert-danger">
    Henüz bir İlan Eklenmemiş

</div>
{% endif %}
{% endblock slider %}

neos_kariyer/user_operations/templates/ads_temp/ilan_ekle.html
{% extends "homebase.html" %}
{% block slider %}
{% load crispy_forms_tags %}
<br>
<br>




<div class="row">
    
      <!--<div class="col-md-4 col-4 mr-4 text-center"><h5><b>İlan Kategorisi</b></h5>
            <form action="." method="post">
                <input type="text" name="s">
            </form>
            </div>-->
            <div class="col-12 text-center" >
        <h3>İlan  Oluştur</h3>
    </div>
        <hr>
        <form action="." method = "post" enctype="multipart/form-data">
            <div class="container"> 
                <div class="row gx-5">
                
            <div class="col-md-4 col-4 mr-4 text-center" >
                {% csrf_token %}
            </div>
            <label for="cars">Aranan Deneyim:</label>

            <select name="cars" id="cars">
                {% for i in  deneyimler %}
            <option value="{{i.id}}">{{i.tecrube}}</option>
                {% endfor %}
            </select>

            <label for="z">İlan Kategorisi:</label>
            <select name="haft" id="z">
                {% for i in  ilan_calisma_saati %}
            <option value="{{i.id}}">{{i.kategory_ismi}}</option>
                {% endfor %}
            </select>
            <label for="m">İlan Ücretlendirmesi:</label>
            <select name="ucretlendirmeler" id="m">
                {% for i in  ilan_ucretlendirmesi %}
            <option value="{{i.id}}">{{i.ucretlendirmesi}}</option>
                {% endfor %}
            </select>
            <label for="k">İlan Lokasyon:</label>
            <select name="lokasyon" id="k">
                {% for i in  lokasyonlar %}
            <option value="{{i.id}}">{{i.sehir_ismi}}</option>
                {% endfor %}
            </select>
            <div class="col-md-7 col-12" >
                <label for="ilanismi" style="width: 200px;"> İlan Başlığı : </label> {{form.ilan_basligi}}<br><br>
                <label for="ilanismi" style="width: 200px;"> İlan Kısa Açıklama : </label> {{form.kisa_ilan_aciklamasi}}<br>
                <label for="ilanismi"> İlan Detayı :</label>{{form.media}} {{form.ilan}}<br><br>
                <label for="ilanismi" style="width: 200px;"> İlan Görseli :</label> {{form.İlan_gorseli}}<br><br>
                <label for="ilanismi" style="width: 200px;"> Maksimum Ücret :</label> {{form.max_ucret}}<br><br>
                <label for="ilanismi" style="width: 200px;"> Minimum Ücret :</label> {{form.min_ucret}}<br>
            {% csrf_token %}
            
            <br>
            <button type = "submit" class = "btn btn-danger">İlan Ekle</button>
            </div>
        </div>
    </div>
            
            
        </form>
    
  </div>

{% endblock slider %}
{% include "scripts.html" %}

neos_kariyer/user_operations/templates/ads_temp/update.html
{% extends "homebase.html" %}

{% block slider %}

<div class="row">
<div class="row mt-5">
    <div class="col-12 text-center" >
        <h3>İlan  Güncelle</h3>
    </div>
        <hr>
        
        <form  method = "post" enctype="multipart/form-data">
            <div class="container"> 
                <div class="row gx-5">
            <div class="col-md-1 col-1 mr-1 text-cente" >
                {% csrf_token %}
            </div>
            <label for="cars">Aranan Deneyim:</label>

            <select name="cars" id="cars">
                {% for i in  deneyimler %}
            <option value="{{i.id}}">{{i.tecrube}}</option>
                {% endfor %}
            </select><br>

            <label for="z">İlan Kategorisi:</label>
            <select name="haft" id="z">
                {% for i in  ilan_calisma_saati %}
            <option value="{{i.id}}">{{i.kategory_ismi}}</option>
                {% endfor %}
            </select><br>
            <label for="m">İlan Ücretlendirmesi:</label>
            <select name="ucretlendirmeler" id="m">
                {% for i in  ilan_ucretlendirmesi %}
            <option value="{{i.id}}">{{i.ucretlendirmesi}}</option>
                {% endfor %}
            </select><br>
            <label for="k">İlan Lokasyon:</label>
            <select name="lokasyon" id="k">
                {% for i in  lokasyonlar %}
            <option value="{{i.id}}">{{i.sehir_ismi}}</option>
                {% endfor %}
            </select>
            <div class="col-md-10 col-12" >
                <br><br>
                <label for="ilanismi" style="width: 200px;"> İlan Başlığı : </label> {{form.ilan_basligi}}<br><br>
                <label for="ilanismi" style="width: 200px;"> İlan Kısa Açıklama : </label> {{form.kisa_ilan_aciklamasi}}<br>
                <label for="ilanismi"> İlan Detayı :</label>{{form.media}} {{form.ilan}}<br><br>
                <label for="ilanismi" style="width: 200px;"> İlan Görseli :</label> {{form.İlan_gorseli}}<br><br>
               
            {% csrf_token %}
            
            <br>
            <button type = "submit" class = "btn btn-danger">İlan Güncelle</button>
            <br><br>
            </div>
        </div>
    </div>
            
            
        </form>
  </div><br>

</div>
{% endblock slider %}