neos_kariyer/ads/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "ads"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addads/',views.addads,name = "add_ads"),
    path('adsupdate/<int:id>',views.updateads,name = "ads_update"),
    path('adsdelete/<int:id>',views.ads_delete,name = "ads_delete"),
    path('views/<int:id>',views.ads_views_offer,name = "ads_views_offer"),
]

neos_kariyer/neos_kariyer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from home.views import *
from all_category.views import mail_gonderme
urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include("user_operations.urls")),
    path('',home_index,name="index"),
    path('ads/',include("ads.urls")),
    path('profile/',include("profil.urls")),
    path('views/',include("offer.urls")),
    #path('buy/',include("pay.urls")),
    path('mail/',mail_gonderme,name = "mail"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

neos_kariyer/offer/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "adsoffer"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "offerdashboard"),
    path('adsshow/<int:id>',views.ads_show,name = "adsshow"),
    path('allads/',views.all_show_ads,name = "allads"),
    path('offerdelete/<int:id>',views.offer_delete,name = "offer_delete"),
    path('inbox/',views.expert_offer_views,name = "inbox"),
    path('allexpert/',views.expert_views_all,name = "allexpert"),
    path('delete/<int:id>',views.alinan_uzman_tekliflerini_sil,name = "alinan_uzman_tekliflerini_sil"),
    path('ilandavet/<int:id>/<int:users>',views.ilana_davet,name = "ilan_davet"),
    path('veto/<int:id>',views.alinan_uzman_tekliflerini_red,name = "alinan_uzman_tekliflerini_red"),
    path('onayla/<int:id>',views.alinan_uzman_tekliflerini_onayla,name = "alinan_uzman_tekliflerini_onayla"),
    path('deletet/<int:id>',views.aldigin_ilan_teklifleri_sil,name = "aldigin_ilan_teklifleri_sil"),
    path('vetot/<int:id>',views.aldigin_ilan_teklifleri_red,name = "aldigin_ilan_teklifleri_red"),
    path('onaylat/<int:id>',views.aldigin_ilan_teklifleri_onayla,name = "aldigin_ilan_teklifleri_onayla"),
]

neos_kariyer/profil/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "profile"

urlpatterns = [
    path('profil/',views.master_user_profile,name = "profile"),
    path('profiledit/',views.profil_edit,name = "profiledit"),
    path('company/',views.master_company_profile,name = "company"),
    path('ozgecmis/<int:id>',views.ozgecmis_sil,name = "ozgecmis_sil"),
    path('openprofile/<int:id>',views.prof_ac,name = "profilac"),
    path('showprofile/<int:id>',views.profil_show,name = "profileshow"),
    path('userprofile/<int:id>',views.company_show,name = "userprofile"),
    path('companyshow/<int:id>',views.company_showw,name = "company_showw"),
    path('yetenek/',views.programlama_di,name="yetenek"),
    path('yetenekekle/',views.yetenek_olusturma,name="yetenekekle"),
    path('yeteneksil/',views.yetenek_sil,name = "yeteneksil"),
    path('favuserekle/',views.fav_user_ekle,name = "fav_user_ekle"),
    path('favusersil/',views.fav_user_sil,name = "fav_user_sil"),
    path('favilanekle/',views.fav_ilan_ekle,name = "fav_ilan_ekle"),
    path('favilansil/',views.fav_ilan_sil,name = "fav_ilan_sil"),
    path('favorilerim/',views.favorilerim,name = "favorilerim"),
    path('degerlendirme_sil/<int:id>',views.degerlendirme_sil,name = "degerlendirme_sil"),
]

neos_kariyer/user_operations/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user_operations"

urlpatterns = [
    path('register/',views.user_register,name = "register"),
    path('login/',views.user_login,name = "login"),
    path('logout/',views.user_logout,name = "logout"),
    path('reset/<int:idim>/<int:kod>',views.parola_sifirlama,name = "reset"),
    path('passrest/',views.pass_reset,name="passreset"),
    path('kod/',views.email_gonder,name = "email_gonder"),
    path('membership/<int:id>',views.membership,name = "membership"),

]

neos_kariyer/ads/forms.py
from django import forms
from .models import *
class is_ilan(forms.ModelForm):
    class Meta:
        model = ads_data
        fields = ["ilan_basligi","kisa_ilan_aciklamasi","ilan","İlan_gorseli"]

neos_kariyer/ads/views.py
from .forms import *
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import *
from offer.models import *
from all_category.models import *
from user_operations.models import user_status
from datetime import date as datetime  ,timedelta
# Create your views here.
#enddate = startdate - timedelta(days=7) +timedelta(days=1)
#startdate = datetime.today() +timedelta(days=7)
#İlan Ekleme Fonksiyonu İcinde Obje Oluşturulur
def addads(request):
    if request.user.is_authenticated:
        if user_status.objects.filter(user_id = request.user):
            pass
        else:
            return redirect("/user/membership/3")
    form = is_ilan(request.POST or None,request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        m = datetime.today() + timedelta(days=7)
        print(m)
        article.ilan_sahibi = request.user
        article.ilan_gecis_tablosu = m
        article.chip_amunt = 0
        article.offer_much = 0

        article.save()
        category_ads.objects.create(ilan_id=article.id,
        aranan_deneyim_id=request.POST.get("cars"),
        lokasyon_id = request.POST.get("lokasyon"),
        ilan_calima_saati_id=request.POST.get("haft"),
        ilan_ucretlendirmesi_id=request.POST.get("ucretlendirmeler"))
        print(request.POST)
        return redirect("/ads/views/"+str(article.id))

    deneyimler = deneyim.objects.all()
    lokasyonlar = lokasyon.objects.all()
    ilan_calisma_saati = kategoriler.objects.all()
    ilan_ucretlendirmesi = ucretlendirme.objects.all()
    sozluk = {"form":form,
    "deneyimler":deneyimler,
    "ilan_calisma_saati":ilan_calisma_saati,
    "ilan_ucretlendirmesi":ilan_ucretlendirmesi,
    "lokasyonlar":lokasyonlar}
    return render(request,"ads_temp/ilan_ekle.html",sozluk)
#İlanların Yönetim Panelidir Ve Sİl Güncelle İçinde Barındırır
def dashboard(request):
    if request.user.is_authenticated:
        if user_status.objects.filter(user_id = request.user):
            pass
        else:
            return redirect("/user/membership/3")
    articles = ads_data.objects.filter(ilan_sahibi = request.user).order_by("-ilan_olusturma_tarihi")
    offers = ad_offer_user.objects.order_by("offer_amount")
    for i in articles:
        z = 0
        for j in offers:
            if i.id == j.ads_ofer_id:
                z = z+1
        ads_data.objects.filter(id = i.id).update(offer_much = z)
        m = 0
        for j in offers:
            if i.id == j.ads_ofer_id:
                m = j.offer_amount
                ads_data.objects.filter(id = i.id).update(chip_amunt = m)
                break
            else:
                ads_data.objects.filter(id = i.id).update(chip_amunt = m)
        if i.offer_much == 0:
            ads_data.objects.filter(id = i.id).update(chip_amunt = 0)
    articles = ads_data.objects.filter(ilan_sahibi = request.user).order_by("-ilan_olusturma_tarihi")
    offers = ad_offer_user.objects.order_by("offer_amount")
    context = {
        "articles":articles,
        "offers":offers
        
    }
    return render(request,"ads_temp/dashboard.html",context)
#İlan Güncelleme Sayfasıdır
from django.utils import timezone

def updateads(request,id):
    if request.user.is_authenticated:
        if user_status.objects.filter(user_id = request.user):
            pass
        else:
            return redirect("/user/membership/3")
    article = get_object_or_404(ads_data,id = id)
    ilan = ads_data.objects.filter(id = id)
    for i in ilan:
        suan = i.ilan_gecis_tablosu
    print(type(suan),"selam")
    #now = timezone.now()
    if suan < timezone.now():
        suan =  timezone.now()
    form = is_ilan(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.ilan_gecis_tablosu = suan+ timedelta(days=7)
        category_ads.objects.filter(ilan_id=id).update(
        aranan_deneyim_id=request.POST.get("cars"),
        lokasyon_id = request.POST.get("lokasyon"),
        ilan_calima_saati_id=request.POST.get("haft"),
        ilan_ucretlendirmesi_id=request.POST.get("ucretlendirmeler"))
        article.save()
        
        messages.success(request,"İlan başarıyla güncellendi")
        return redirect("ads:dashboard")

    deneyimler = deneyim.objects.all()
    lokasyonlar = lokasyon.objects.all()
    ilan_calisma_saati = kategoriler.objects.all()
    ilan_ucretlendirmesi = ucretlendirme.objects.all()
    sozluk = {"form":form,
    "deneyimler":deneyimler,
    "ilan_calisma_saati":ilan_calisma_saati,
    "ilan_ucretlendirmesi":ilan_ucretlendirmesi,
    "lokasyonlar":lokasyonlar}
    return render(request,"ads_temp/update.html",sozluk)

#İlan Silme Fonksiyonudur
def ads_delete(request,id):
    if request.user.is_authenticated:
        if user_status.objects.filter(user_id = request.user):
            pass
        else:
            return redirect("/user/membership/3")
    article = get_object_or_404(ads_data,id = id)

    article.delete()

    messages.success(request,"İlan Başarıyla Silindi")

    return redirect("ads:dashboard")
#ilan detay teklif gösterme 
def ads_views_offer(request,id):
    try:
        acik = ad_offer_user.objects.filter(ads_ofer_id = id).order_by("-offer_amount")
        a = ads_data.objects.filter(id = id)
        ads_filter = category_ads.objects.filter(ilan_id = id)
        z = 1
    except:
        pass
    all_profil = user_profil.objects.all()
    print(all_profil)
    data = {"ads":a,"ads_filter":ads_filter,"acik":acik,"z":z,"all_profil":all_profil}
    return render(request, "offer_temp/ads_views.html",data)

neos_kariyer/user_operations/views.py
from django.shortcuts import render ,HttpResponse
from django.utils.datastructures import MultiValueDictKeyError
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from .models import *

# Create your views here.
#Kullanıcı Giriş Bölümü
def user_login(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            #messages.info(request,"Kullanıcı Adı veya Parola Hatalı")
            return render(request,"user_operations_temp/login.html",context)

        messages.success(request,"Başarıyla Giriş Yaptınız")
        login(request,user)
        #return redirect("index")
    return render(request, "user_operations_temp/login.html",context)
#Kullanını Kayıt Sayfasıdır.
def user_register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        newUser = User(username =username,email=email)
        newUser.set_password(password)
        try:
            newUser.save()
            login(request,newUser)
            messages.info(request,"Başarıyla Kayıt Oldunuz...")
            return redirect("/user/membership/3")
        except:
            messages.info(request,"İstediğiniz Kullanıcı Adı Kullanılmaktadır...")
            return redirect("/user/register/")
        
    context = {
            "form" : form
        }
    return render(request,"user_operations_temp/register.html",context)
def user_logout(request):
    logout(request)
    messages.success(request,"Başarıyla Çıkış Yaptınız")
    return redirect("index")
#Kullanıcı Druumlarını Düzenliyip Obje Oluşturulan Yerdir Bağlanti Models.py dir
def membership(request,id):
    if id == 3:
        print("Selamlar")
    elif id == 1:
        z  = user_status.objects.create(durum = 1)
        z.user = request.user
        z.save()
        return redirect("/profile/profil/")
    elif id == 0:
        z  = user_status.objects.create(durum = 0)
        z.user = request.user
        z.save()
        return redirect("/profile/company/")
    return render(request, "user_operations_temp/membership.html")
import random
from django.core.mail import send_mail
def email_gonder(request):
    print("Selam")
    username = request.POST.get('dili')
    mail_alindi = 0
    for i in username:
        if i == "@":
            mail_alindi = 1
            break
    if mail_alindi == 1:
        m = User.objects.filter(email=username)
        for i in m :
            idim = i.id
            mail = i.email
        try:
            ker = parola_sifirla.objects.filter(user_id = idim)
            
            print(ker)
        except:
            ker = 0
        if ker:
            gonder = random.randint(111111, 999999)
            print(gonder)
            parola_sifirla.objects.filter(user_id=idim).update(sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        else:
            gonder = random.randint(111111, 999999)
            parola_sifirla.objects.create(user_id=idim,sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        return redirect("/user/reset/")
    else:
        m = User.objects.filter(username=username)
        for i in m :
            idim = i.id
            mail = i.email
        try:
            ker = parola_sifirla.objects.filter(user_id = idim)
            
            print(ker)
        except:
            ker = 0
        if ker:
            gonder = random.randint(111111, 999999)
            print(gonder)
            parola_sifirla.objects.filter(user_id=idim).update(sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        else:
            gonder = random.randint(111111, 999999)
            parola_sifirla.objects.create(user_id=idim,sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        return redirect("/user/passrest/")
from .forms import passreset
def parola_sifirlama(request,idim,kod):
    form = passreset(request.POST or None)
    if form.is_valid():
        password = form.cleaned_data.get("password")
        user = User.objects.get(id=idim)
        print(idim)
        if parola_sifirla.objects.filter(user_id = idim,sifirla=kod):
            user.set_password(password)
            user.save()
            messages.success(request, "Parola Sıfırlandı")
            return redirect("/user/login/")
        else:
            messages.success(request, "Kullanıcı Bulunamadı")
            return redirect("/user/reset/")
    return render(request, "user_operations_temp/password_reset.html",{"form":form})

def pass_reset(request):
    if request.POST:
        users = request.POST.get("bilgi")
        print(users)
        kod = request.POST.get("dogrulaemail")
        print(kod)
        mail_alma = 0

        if users and kod :
            print("if 1")
            for i in users:
                if i == "@":
                    mail_alma = 1
                    print("if 2")
                    break
            if mail_alma:
                print("if 3")
                m = User.objects.filter(email=users)
                for i in m:
                    idim = i.id
                user = User.objects.get(id=idim)
                if parola_sifirla.objects.filter(user_id = idim,sifirla=kod):
                    print("kod Doğru",kod)
                    return redirect("/user/reset/"+str(idim)+"/"+str(kod))
                    
            else:
                print("if 3")
                m = User.objects.filter(username=users)
                for i in m:
                    idim = i.id
                user = User.objects.get(id=idim)
                if parola_sifirla.objects.filter(user_id = idim,sifirla=kod):
                    print("kod Doğru",kod)
                    return redirect("/user/reset/"+str(idim)+"/"+str(kod))
        else:   
            print("else 1")
    return render(request, "user_operations_temp/first_pass_reset.html")

neos_kariyer/user_operations/templates/offer_temp/ads_offer_dashboard.html
{% extends "homebase.html" %}
{% load static %}
{% block slider %}
<div class="container-lg">

    <div class="row">

        <div class="col-12">
            <!--sıralama-->
            <div class="row">
                <div class="col">
                    
                </div>
                <div class="col">
                    <div class="input-group mb-3">
                        
                    </div>
                </div>
            </div>
            <!--**sıralama**-->
            
            <!--ilanlar-->
            {% for i in offers %} 
            <h6>Teklif vermiş olduğunuz ilanlar
            </h6>
                {% for j in articles %}
                    {% if i.ads_ofer_id == j.id %}
                        <div class="card">
                            <h6 class="card-header">{{j.ilan_basligi}}
                                {% if i.veto_status %}
                                <p  style=" color: red; float:right" >Red Edildi</p>
                                {% else %}
                                    {% if i.acceptance_status %}
                                
                                        <p style="float:right; color: green;" >Onaylandı</p>
                                    {% else %}
                                        <p style="float:right; color: green;" >Beklemede</p>
                                    {% endif %}
                                {% endif %}
                            </h6>
                            <div class="card-body py-1">
                                <div class="row">
                                    {% if j.İlan_gorseli %}
                                        <div class="col-12 col-lg-2 text-center"><img src="{{j.İlan_gorseli.url}}" class="kategori-img">
                                    {% else %}
                                    
                                        <div class="col-12 col-lg-2 text-center"><img src="{% static 'images/dijital.png' %}" class="kategori-img">
                                    {% endif %}
                                    </div>
                                    <div class="col-12 col-lg-10">
                                        <p class="card-text">
                                            {{j.kisa_ilan_aciklamasi}}
                                        </p>
                                        <small class="card-text"><span class="detay">{{j.offer_much}} Teklif | Son 4 Gün | Deneyim: Farketmez
                                                | </span> <b class="price">{{j.min_ucret}}₺ - {{j.max_ucret}}₺</b>
                                        </small> <br>
                                        <small class="card-text"><span class="detay">En düşük teklif: <b>{{j.chip_amunt}} ₺</b> | Senin
                                                teklifin: <b style="color:green">{{i.offer_amount}} ₺</b> | İlan durumu: <b
                                                    style="color:green;">Açık</b>
                                            </span>
                                        </small>
                                        {% if i.veto_status %}
                                        <a href="{% url 'adsoffer:offer_delete' i.id %}" style="margin-left: 5px;" class="btn btn-sm apply-button btn-outline-danger">Sil</a>
                                        <a href="{% url 'adsoffer:adsshow' j.id %}" style="margin-left: 5px;" class="btn btn-sm apply-button btn-outline-success">Güncelle</a>
                                       
                                        {% else %}
                                            {% if i.acceptance_status %}
                                        
                                                <p style="float:right; color: green;" >Kabul Edildi</p>
                                            {% else %}
                                            <a href="{% url 'adsoffer:offer_delete' i.id %}" style="margin-left: 5px;" class="btn btn-sm apply-button btn-outline-danger">Sil</a>
                                            <a href="{% url 'adsoffer:adsshow' j.id %}" style="margin-left: 5px;" class="btn btn-sm apply-button btn-outline-success">Güncelle</a>
                                            
                                            {% endif %}
                                        {% endif %}
                                        
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% else %}
                    
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <!--**ilanlar**-->
            
           
            <!--**ilanlar**-->
        </div>
    </div>
</div>
<div class="container-lg">

    <div class="row">
        <!--filtre-->
        <div class="col-lg-3 col-md-5 col-12">
            <div class="vertical-card-div filtre" style="top: 10%;">
             
                
            </div>
        </div>
        <!--**filtre**-->
  
  
        <div class="col-lg-9 col-md-7 col-12">
            <!--sıralama-->
            <div class="row">
                <div class="col">
                   
                   
                    
                  
                    
                </div>
                <div class="col">
                    <div class="input-group mb-3">
                      
                    </div>
                </div>
            </div>
     
  
            <!--**sıralama**-->
  
            <!--uzmanlar-->
            <div class="row justify-content-center">
            <h6>İlana Davet Edilen Uzmanlar
            </h6>
              {% for k in ilana_davet_edilen %}
              {% for ilanlar in ilanlarim %}

              {% for j in uzman2 %}
              {% for i in uzman %}
              {% if ilanlar.id == k.ads_ofer_id %}
              
              {% if k.offer_user_id == i.id %}
              
              
              {% if i.user_id != request.user.id %}
                {% if i.user_id == j.user_id %}
                
                <div class="col-lg-3 col-6 ">
                    <div class="card uzman-card">
                        {% if i.profil_img  %}
                        <a href="{% url 'profile:profileshow' i.id %}">
                        <img src="{{i.profil_img.url}}" class="card-img-top" alt="..."></a>
                        {% else %}
                        <a href="{% url 'profile:profileshow' i.id %}">
                        <img src="{% static 'images/hero.jpg' %}" class="card-img-top" alt="..."></a>
                        {% endif %}
                        <div class="card-body">
                            <h6 class="card-title">{{i.user_kategori}}</h6>
                            <h6 class="card-subtitle text-muted" style="font-size:13px;">{{i.isim_soyisim}}</h6>
                            <div class="kisisel-bilgiler">
                                <div style="display:inline;"><img src="{% static 'images/ikonlar/1.png' %}"><small>{{i.lokasyon}}</small>
                                </div>
                                <div style="display:inline;margin-left:5px;"><img
                                        src="{% static 'images/ikonlar/7.png' %}"><small>{{j.deneyim}}
                                    </small>
                                </div>
                            </div>
                            <p class="card-text uzman-text">{{i.on_bilgi}}
                              {% if ilan_yapma %}
                              {% else %}
                              <b class="price"></b> | 
                              
  
                              {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
              {% else %}
               {% endif %}
              {% else %}
                {% endif %}
               {% else %}
               
              {% endif %}
              {% else %}
                {% endif %}
              {% endfor %}
            {% endfor %}
            {% endfor %}
            {% endfor %}
            <!--**uzmanlar**-->
        
  
  
  
    
    
  
  <hr>
  <!--uzmanlar-->
            <div class="row justify-content-center">
              {% for k in calismak_icin_verilen_teklifler %}
              <h6>Çalışmak İçin Teklif Verdiğiniz Kullanıcılar
            </h6>

              {% for j in uzman2 %}
              {% for i in uzman %}

              {% if k.expert_offers_user_id == i.user_id %}
              
              
              {% if i.user_id != request.user.id %}
                {% if i.user_id == j.user_id %}
                
                <div class="col-lg-3 col-6 ">
                    <div class="card uzman-card">
                        {% if i.profil_img  %}
                        <a href="{% url 'profile:profileshow' i.id %}">
                        <img src="{{i.profil_img.url}}" class="card-img-top" alt="..."></a>
                        {% else %}
                        <a href="{% url 'profile:profileshow' i.id %}">
                        <img src="{% static 'images/hero.jpg' %}" class="card-img-top" alt="..."></a>
                        {% endif %}
                        <div class="card-body">
                            <h6 class="card-title">{{i.user_kategori}}</h6>
                            <h6 class="card-subtitle text-muted" style="font-size:13px;">{{i.isim_soyisim}}</h6>
                            <div class="kisisel-bilgiler">
                                <div style="display:inline;"><img src="{% static 'images/ikonlar/1.png' %}"><small>{{i.lokasyon}}</small>
                                </div>
                                <div style="display:inline;margin-left:5px;"><img
                                        src="{% static 'images/ikonlar/7.png' %}"><small>{{j.deneyim}}
                                    </small>
                                </div>
                            </div>
                            <p class="card-text uzman-text">{{i.on_bilgi}}
                              {% if ilan_yapma %}
                              {% else %}
                              <b class="price"></b> | 
                              
  
                              {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
              {% else %}
               {% endif %}
              {% else %}
                {% endif %}
               {% else %}
               
              {% endif %}
              
              {% endfor %}
            {% endfor %}
            
            {% endfor %}
            <!--**uzmanlar**-->
        
  </div>
  </div>
  <br><br>
  {% if uzman.has_other_pages %}
  
  <nav  aria-label="Page navigation example">
  
    <ul class="pagination justify-content-center">
  {% if uzman.has_previous %}
  <li class="page-item"><a class="page-link" href="?sayfa={{ uzman.previous_page_number }}">Geri</a></li>
  {% else %}
  <li class="page-item disabled">
  <p class="disabled" ><span class="page-link">Geri</span></p></li>
  {% endif %}
  {% for i in uzman.paginator.page_range %}
  {% if uzman.number == i %}
  <li class="page-item"><a class="page-link"  href="?sayfa={{ i }}"><u>{{ i }}</u></a></li>
  {% else %}
  <li class="page-item"><a class="page-link"  href="?sayfa={{ i }}">{{ i }}</a></li>
  {% endif %}
  {% endfor %}
  {% if uzman.has_next %}
  <li class="page-item"><a class="page-link"  href="?sayfa={{ uzman.next_page_number }}">İleri</a></li>
  
  {% else %}
  <li class="page-item disabled">
    <p class="disabled"><span class="page-link">İleri</span></p></li>
  
  {% endif %}
  </ul>
  
  </nav>
  
  {% endif %}
  </div>
  
  </div>
  
  
  
  </div>
  <!--offcanvas filtre-->
  <nav class="navbar navbar-light bg-light fixed-bottom mycanvas">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Detaylı arama</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
            aria-controls="offcanvasNavbar">
            <span><img src="images/filter.png" style="width:40px"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
            aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                    aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                
            </div>
        </div>
    </div>
  </nav>  
  
  
  <script>
  $(document).ready(function () {
  $(".yetenekler").click(function (event) {
   id = $(this).attr("id"),
  $.ajax({
    type: "POST",
    url: "/profile/favuserekle/",
    data: {
      id: id,
      csrfmiddlewaretoken: '{{ csrf_token }}'
    },
    
  });
  return false; //<---- move it here
  });
  });
  </script>

{% endblock slider %}