neos_kariyer/ads/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "ads"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addads/',views.addads,name = "add_ads"),
    path('adsupdate/<int:id>',views.updateads,name = "ads_update"),
    path('adsdelete/<int:id>',views.ads_delete,name = "ads_delete"),
    path('views/<int:id>',views.ads_views_offer,name = "ads_views_offer"),
]

neos_kariyer/neos_kariyer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from home.views import *
from all_category.views import mail_gonderme
urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include("user_operations.urls")),
    path('',home_index,name="index"),
    path('ads/',include("ads.urls")),
    path('profile/',include("profil.urls")),
    path('views/',include("offer.urls")),
    #path('buy/',include("pay.urls")),
    path('mail/',mail_gonderme,name = "mail"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

neos_kariyer/offer/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "adsoffer"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "offerdashboard"),
    path('adsshow/<int:id>',views.ads_show,name = "adsshow"),
    path('allads/',views.all_show_ads,name = "allads"),
    path('offerdelete/<int:id>',views.offer_delete,name = "offer_delete"),
    path('inbox/',views.expert_offer_views,name = "inbox"),
    path('allexpert/',views.expert_views_all,name = "allexpert"),
    path('delete/<int:id>',views.alinan_uzman_tekliflerini_sil,name = "alinan_uzman_tekliflerini_sil"),
    path('ilandavet/<int:id>/<int:users>',views.ilana_davet,name = "ilan_davet"),
    path('veto/<int:id>',views.alinan_uzman_tekliflerini_red,name = "alinan_uzman_tekliflerini_red"),
    path('onayla/<int:id>',views.alinan_uzman_tekliflerini_onayla,name = "alinan_uzman_tekliflerini_onayla"),
    path('deletet/<int:id>',views.aldigin_ilan_teklifleri_sil,name = "aldigin_ilan_teklifleri_sil"),
    path('vetot/<int:id>',views.aldigin_ilan_teklifleri_red,name = "aldigin_ilan_teklifleri_red"),
    path('onaylat/<int:id>',views.aldigin_ilan_teklifleri_onayla,name = "aldigin_ilan_teklifleri_onayla"),
]

neos_kariyer/profil/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "profile"

urlpatterns = [
    path('profil/',views.master_user_profile,name = "profile"),
    path('profiledit/',views.profil_edit,name = "profiledit"),
    path('company/',views.master_company_profile,name = "company"),
    path('ozgecmis/<int:id>',views.ozgecmis_sil,name = "ozgecmis_sil"),
    path('openprofile/<int:id>',views.prof_ac,name = "profilac"),
    path('showprofile/<int:id>',views.profil_show,name = "profileshow"),
    path('userprofile/<int:id>',views.company_show,name = "userprofile"),
    path('companyshow/<int:id>',views.company_showw,name = "company_showw"),
    path('yetenek/',views.programlama_di,name="yetenek"),
    path('yetenekekle/',views.yetenek_olusturma,name="yetenekekle"),
    path('yeteneksil/',views.yetenek_sil,name = "yeteneksil"),
    path('favuserekle/',views.fav_user_ekle,name = "fav_user_ekle"),
    path('favusersil/',views.fav_user_sil,name = "fav_user_sil"),
    path('favilanekle/',views.fav_ilan_ekle,name = "fav_ilan_ekle"),
    path('favilansil/',views.fav_ilan_sil,name = "fav_ilan_sil"),
    path('favorilerim/',views.favorilerim,name = "favorilerim"),
    path('degerlendirme_sil/<int:id>',views.degerlendirme_sil,name = "degerlendirme_sil"),
]

neos_kariyer/user_operations/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user_operations"

urlpatterns = [
    path('register/',views.user_register,name = "register"),
    path('login/',views.user_login,name = "login"),
    path('logout/',views.user_logout,name = "logout"),
    path('reset/<int:idim>/<int:kod>',views.parola_sifirlama,name = "reset"),
    path('passrest/',views.pass_reset,name="passreset"),
    path('kod/',views.email_gonder,name = "email_gonder"),
    path('membership/<int:id>',views.membership,name = "membership"),

]

neos_kariyer/user_operations/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# kullanıcıların şirketmi yoksa freelancermi olduğunu belirler.
class user_status(models.Model):
    user = models.OneToOneField(User,null=True,on_delete = models.CASCADE,verbose_name="Kullanıcı Durumu")
    durum = models.BooleanField(null=True)

class parola_sifirla(models.Model):
    user = models.OneToOneField(User,null=True,on_delete = models.CASCADE,verbose_name="Kullanıcı Durumu")
    sifirla = models.IntegerField()

neos_kariyer/user_operations/forms.py
from django import forms
from django.forms import widgets

class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanıcı Adı" , widget=forms.TextInput(attrs={'placeholder': 'Kullanıcı Adı', 'class': 'form-control'}))
    password = forms.CharField(label = "Parola",widget = forms.PasswordInput(attrs={'placeholder': 'Parola', 'class': 'form-control'}))


class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50,label = "Kullanıcı Adı",widget=forms.TextInput(attrs={'class': "form-control", 
                'style': 'max-width: 600px;',
                'placeholder': 'Kullanıcı Adı'}))
    email = forms.EmailField(max_length=100,label = "Email",widget=forms.EmailInput(attrs={'class': "form-control", 
                'style': 'max-width: 600px;',
                'placeholder': 'E-Posta'}))
    password = forms.CharField(max_length=20,label = "Parola",widget = forms.PasswordInput(attrs={'class': "form-control", 
                'style': 'max-width: 600px;',
                'placeholder': 'Parola'}))
    confirm = forms.CharField(max_length=20,label ="Parolayı Doğrula",widget = forms.PasswordInput(attrs={'class': "form-control", 
                'style': 'max-width: 600px;',
                'placeholder': 'Parola Doğrula'}))
    
    def clean(self):
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm and len(password)<6:
            raise forms.ValidationError("Parola Hatalı")

        values = {
            "username" : username,
            "password" : password,
            "email"  : email
        }
        return values



class passreset(forms.Form):
    password = forms.CharField(max_length=20,label = "Parola",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="Parolayı Doğrula",widget = forms.PasswordInput)
    
    def clean(self):
        
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar Eşleşmiyor")

        values = {
            
            "password" : password
        }
        return values

neos_kariyer/user_operations/views.py
from django.shortcuts import render ,HttpResponse
from django.utils.datastructures import MultiValueDictKeyError
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from .models import *

# Create your views here.
#Kullanıcı Giriş Bölümü
def user_login(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            #messages.info(request,"Kullanıcı Adı veya Parola Hatalı")
            return render(request,"user_operations_temp/login.html",context)

        messages.success(request,"Başarıyla Giriş Yaptınız")
        login(request,user)
        #return redirect("index")
    return render(request, "user_operations_temp/login.html",context)
#Kullanını Kayıt Sayfasıdır.
def user_register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        newUser = User(username =username,email=email)
        newUser.set_password(password)
        try:
            newUser.save()
            login(request,newUser)
            messages.info(request,"Başarıyla Kayıt Oldunuz...")
            return redirect("/user/membership/3")
        except:
            messages.info(request,"İstediğiniz Kullanıcı Adı Kullanılmaktadır...")
            return redirect("/user/register/")
        
    context = {
            "form" : form
        }
    return render(request,"user_operations_temp/register.html",context)
def user_logout(request):
    logout(request)
    messages.success(request,"Başarıyla Çıkış Yaptınız")
    return redirect("index")
#Kullanıcı Druumlarını Düzenliyip Obje Oluşturulan Yerdir Bağlanti Models.py dir
def membership(request,id):
    if id == 3:
        print("Selamlar")
    elif id == 1:
        z  = user_status.objects.create(durum = 1)
        z.user = request.user
        z.save()
        return redirect("/profile/profil/")
    elif id == 0:
        z  = user_status.objects.create(durum = 0)
        z.user = request.user
        z.save()
        return redirect("/profile/company/")
    return render(request, "user_operations_temp/membership.html")
import random
from django.core.mail import send_mail
def email_gonder(request):
    print("Selam")
    username = request.POST.get('dili')
    mail_alindi = 0
    for i in username:
        if i == "@":
            mail_alindi = 1
            break
    if mail_alindi == 1:
        m = User.objects.filter(email=username)
        for i in m :
            idim = i.id
            mail = i.email
        try:
            ker = parola_sifirla.objects.filter(user_id = idim)
            
            print(ker)
        except:
            ker = 0
        if ker:
            gonder = random.randint(111111, 999999)
            print(gonder)
            parola_sifirla.objects.filter(user_id=idim).update(sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        else:
            gonder = random.randint(111111, 999999)
            parola_sifirla.objects.create(user_id=idim,sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        return redirect("/user/reset/")
    else:
        m = User.objects.filter(username=username)
        for i in m :
            idim = i.id
            mail = i.email
        try:
            ker = parola_sifirla.objects.filter(user_id = idim)
            
            print(ker)
        except:
            ker = 0
        if ker:
            gonder = random.randint(111111, 999999)
            print(gonder)
            parola_sifirla.objects.filter(user_id=idim).update(sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        else:
            gonder = random.randint(111111, 999999)
            parola_sifirla.objects.create(user_id=idim,sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        return redirect("/user/passrest/")
from .forms import passreset
def parola_sifirlama(request,idim,kod):
    form = passreset(request.POST or None)
    if form.is_valid():
        password = form.cleaned_data.get("password")
        user = User.objects.get(id=idim)
        print(idim)
        if parola_sifirla.objects.filter(user_id = idim,sifirla=kod):
            user.set_password(password)
            user.save()
            messages.success(request, "Parola Sıfırlandı")
            return redirect("/user/login/")
        else:
            messages.success(request, "Kullanıcı Bulunamadı")
            return redirect("/user/reset/")
    return render(request, "user_operations_temp/password_reset.html",{"form":form})

def pass_reset(request):
    if request.POST:
        users = request.POST.get("bilgi")
        print(users)
        kod = request.POST.get("dogrulaemail")
        print(kod)
        mail_alma = 0

        if users and kod :
            print("if 1")
            for i in users:
                if i == "@":
                    mail_alma = 1
                    print("if 2")
                    break
            if mail_alma:
                print("if 3")
                m = User.objects.filter(email=users)
                for i in m:
                    idim = i.id
                user = User.objects.get(id=idim)
                if parola_sifirla.objects.filter(user_id = idim,sifirla=kod):
                    print("kod Doğru",kod)
                    return redirect("/user/reset/"+str(idim)+"/"+str(kod))
                    
            else:
                print("if 3")
                m = User.objects.filter(username=users)
                for i in m:
                    idim = i.id
                user = User.objects.get(id=idim)
                if parola_sifirla.objects.filter(user_id = idim,sifirla=kod):
                    print("kod Doğru",kod)
                    return redirect("/user/reset/"+str(idim)+"/"+str(kod))
        else:   
            print("else 1")
    return render(request, "user_operations_temp/first_pass_reset.html")

neos_kariyer/user_operations/templates/profil_temp/favorilerim.html
{% extends "homebase.html" %}
{% block slider %}
{% load static %}


<style>
  .hero-image-short{
      background-image: linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)),
  url("{% static 'images/banner_img.jpeg' %}");
  }
</style>

<div class="hero-image-short">
  <div class="hero-text-left">
      <h3 style="color:black"><b>"İzlem Listem" </b> </h3>
  </div>
  <div class="hero-text-right">
      <!--Eğer giriş/kayıt yapılmadıysa bu buton gösterilir-->
      {% if request.user.is_authenticated %}
      {% else %}
      <a class="btn btn-block" href="{% url 'user_operations:register' %}" style="background-color:#004aad"><b
              style="color:white;">Kazanmaya
              başla</b></a>
      {% endif %}
      <!--****-->
  </div>
</div>
<!--content-->
<div class="container-lg">

  <div class="row">
      <!--filtre-->
      <div class="col-lg-3 col-md-5 col-12">
          <div class="vertical-card-div filtre" style="top: 10%;">
            
              
              
          </div>
      </div>
      <!--**filtre**-->


      <div class="col-lg-9 col-md-7 col-12">
          <!--sıralama-->
          <div class="row">
              <div class="col">
                 
                 
                  
                
                  
              </div>
              
          </div>
        

          <!--**sıralama**-->

          <!--uzmanlar-->
          <div class="row justify-content-center">
            
            {% for j in uzman2 %}
            {% for i in uzman %}
            {% for k in all_users %}
                {% if  i.id == k.offer_user_id %}
                
                
            {% if i.user_id != request.user.id %}
            
            
            
              {% if i.user_id == j.user_id %}
              
              <div class="col-lg-3 col-6 ">
                  <div class="card uzman-card">
                      {% if i.profil_img  %}
                      <a href="{% url 'profile:profileshow' i.id %}">
                      <img src="{{i.profil_img.url}}" class="card-img-top" alt="..."></a>
                      {% else %}
                      <a href="{% url 'profile:profileshow' i.id %}">
                      <img src="{% static 'images/hero.jpg' %}" class="card-img-top" alt="..."></a>
                      {% endif %}
                      <div class="card-body">
                          <h6 class="card-title">{{i.user_kategori}}</h6>
                          <h6 class="card-subtitle text-muted" style="font-size:13px;">{{i.isim_soyisim}}</h6>
                          <div class="kisisel-bilgiler">
                              <div style="display:inline;"><img src="{% static 'images/ikonlar/1.png' %}"><small>{{i.lokasyon}}</small>
                              </div>
                              <div style="display:inline;margin-left:5px;"><img
                                      src="{% static 'images/ikonlar/7.png' %}"><small>{{j.deneyim}}
                                  </small>
                              </div>
                          </div>
                          <p class="card-text uzman-text">{{i.on_bilgi}}<b class="price"></b> | <img src="{% static 'images/fav.png' %}"
                            class="yetenekler" type="button"  alt="favori" style="max-width:20px;margin-bottom:5px;" id="{{i.id}}"
                            onmouseover="this.src= {% static 'images/fav-sari.png' %} ;"
                            onmouseout="this.src= {% static 'images/fav.png' %} ;">
                          </p>
                      </div>
                  </div>
              </div>
            {% else %}
             {% endif %}
            {% else %}
              {% endif %}
             {% else %}
                {% endif %}
            {% endfor %}
            {% endfor %}
          {% endfor %}
        
          <!--**uzmanlar**-->
      



  
  


</div>
<br><br>
{% if uzman.has_other_pages %}

<nav  aria-label="Page navigation example">

  <ul class="pagination justify-content-center">
{% if uzman.has_previous %}
<li class="page-item"><a class="page-link" href="?sayfa={{ uzman.previous_page_number }}">Geri</a></li>
{% else %}
<li class="page-item disabled">
<p class="disabled" ><span class="page-link">Geri</span></p></li>
{% endif %}
{% for i in uzman.paginator.page_range %}
{% if uzman.number == i %}
<li class="page-item"><a class="page-link"  href="?sayfa={{ i }}"><u>{{ i }}</u></a></li>
{% else %}
<li class="page-item"><a class="page-link"  href="?sayfa={{ i }}">{{ i }}</a></li>
{% endif %}
{% endfor %}
{% if uzman.has_next %}
<li class="page-item"><a class="page-link"  href="?sayfa={{ uzman.next_page_number }}">İleri</a></li>

{% else %}
<li class="page-item disabled">
  <p class="disabled"><span class="page-link">İleri</span></p></li>

{% endif %}
</ul>

</nav>

{% endif %}
</div>

 <!--ilanlar--><div class="col-lg-8 col-md-7 col-12">
    {% for i in ads %}
    {% for k in all_ads %}
        {% if k.ads_ofer_id == i.id %}
    {% for j in ads_kategori %}
    {% if i.id == j.ilan_id %}
    
        
        
    
    
    <div class="card">
        <h6 class="card-header">{{i.ilan_basligi}}
        </h6>
        <div class="card-body py-1">
            <div class="row">
                {% if i.İlan_gorseli %}
                    <div class="col-12 col-lg-2 text-center"><img src="{{i.İlan_gorseli.url}}" class="kategori-img">
                {% else %}
                    <div class="col-12 col-lg-2 text-center"><img src="{% static 'images/dijital.png' %}" class="kategori-img">
                {% endif %}
                
                </div>
                <div class="col-12 col-lg-10">
                    <p class="card-text">
                       {{i.kisa_ilan_aciklamasi}}
                    </p>
                    <small class="card-text"><span class="detay">{{i.offer_much}} Teklif  | Deneyim: {{j.aranan_deneyim}} | 
                        İlan Ücretlendirmesi :{{j.ilan_ucretlendirmesi}}| İlan Kategorisi : {{j.ilan_calima_saati}}</span>
                        {% if ilan_yapma %}
                    
                     <b class="price"></b> | <img src="{% static 'images/fav.png' %}"
                            alt="favori" style="max-width:20px;margin-bottom:5px;" class="yetenekleri" type="button" id ="{{i.id}}"
                            onmouseover="this.src= {% static 'images/fav-sari.png' %} ;"
                            onmouseout="this.src= {% static 'images/fav.png' %} ;">
                            {% else %}

                    {% endif %}
                    </small>
                    <a href="{% url 'adsoffer:adsshow' i.id %}" class="btn btn-sm apply-button btn-outline-primary">İncele</a>
                </div>
            </div>
        </div>
    </div>
    
    {% else %}
    {% endif %}
    {% endfor %}
    {% else %}
        {% endif %}
    {% endfor %}
    {% endfor %}
    <!--**ilanlar**-->
</div>
</div>
</div>

<!--offcanvas filtre-->
<nav class="navbar navbar-light bg-light fixed-bottom mycanvas">
<div class="container-fluid">
<a class="navbar-brand" href="#">Detaylı arama</a>
<button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
    aria-controls="offcanvasNavbar">
    <span><img src="images/filter.png" style="width:40px"></span>
</button>
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
    aria-labelledby="offcanvasNavbarLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
            aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
   
    </div>
</div>
</div>
</nav>
</div>



</div>
<!--offcanvas filtre-->
<nav class="navbar navbar-light bg-light fixed-bottom mycanvas">
  <div class="container-fluid">
      <a class="navbar-brand" href="#">Detaylı arama</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
          aria-controls="offcanvasNavbar">
          <span><img src="images/filter.png" style="width:40px"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
          aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
              <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                  aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
              
          </div>
      </div>
  </div>
</nav> 

<!--**offcanvas filtre**-->
<script>
    $(document).ready(function () {
    $(".yetenekleri").click(function (event) {
     id = $(this).attr("id"),
    $.ajax({
      type: "POST",
      url: "/profile/favilansil/",
      data: {
        id: id,
        csrfmiddlewaretoken: '{{ csrf_token }}'
      },
      
    });
    return false; //<---- move it here
    });
    });
    </script>

<script>
$(document).ready(function () {
$(".yetenekler").click(function (event) {
 id = $(this).attr("id"),
$.ajax({
  type: "POST",
  url: "/profile/favusersil/",
  data: {
    id: id,
    csrfmiddlewaretoken: '{{ csrf_token }}'
  },
  
});
return false; //<---- move it here
});
});
</script>
{% endblock slider %}

neos_kariyer/user_operations/templates/profil_temp/profil_edit.html
{% extends "homebase.html" %}
{% block slider %}
{% load static %}


        <form method="POST" action="." style="max-width:360px;margin:auto;">
            {% csrf_token %}
            <div class="form-group">
                <label for="name">Şehir</label>
                <select name="sehir" class="form-select" aria-label="Default select example">
                <option selected>Lütfen seçiniz</option>
                {% for i in konum %}
                    
                    <option  value="{{i.id}}">{{i.sehir_ismi}}</option>
                    
                {% endfor %}
                </select>
            </div>
            <br>
            <div class="form-group">
                <label for="email">Uzmanlık alanınız</label>
                <select name="kategori" class="form-select" aria-label="Default select example">
                <option selected>Lütfen seçiniz</option>
                {% for i in kategori %}
                    
                    <option value="{{i.id}}">{{i.kategory_ismi}}</option>
                    
                    {% endfor %}
                </select>
            </div>
            <br>
            <label for="">Alanınızda kaç yıl deneyimlisiniz?</label>
            {% for i in tecrubem %}
            <div class="form-check">
                <input class="form-check-input" type="radio" name="r" value="{{i.id}}" id="r1">
                <label class="form-check-label" for="r1">
                    {{i.tecrube}}
                </label>
            </div>
           {% endfor %}

            <br>
            <label for="">Alacağınız projelere haftada kaç saat zaman ayırabilirsiniz?</label>
            {% for i in saat %}
            
            
            <div class="form-check">
                <input class="form-check-input" type="radio" value="{{i.id}}" name="t" id="t1">
                <label class="form-check-label" for="t1">
                    {{i.calisma_saat}}
                </label>
            </div>
            {% endfor %} <br>
            <label for="">Şu Anda Aktif Çalışma Durumunuz?</label>
            {% for i in calisma_durumum %}
            <div class="form-check">
                <input class="form-check-input" type="radio" value="{{i.id}}" name="work" id="w2">
                <label class="form-check-label" for="t1">
                    {{i.calisma_durumu}}
                </label>
            </div>
            {% endfor %} <br>
            <label for="">Sitede Aktif Olarak Ne Şekilde Çalışmak İstersiniz?</label>
            {% for i in arayis %}
            
            
            <div class="form-check">
                <input class="form-check-input" type="radio" value="{{i.id}}" name="is" id="w2">
                <label class="form-check-label" for="t1">
                    {{i.calisma_beklentisi}}
                </label>
            </div>
            {% endfor %}
            <br>
            <label for="w3review">Kartvizit Bilginiz:</label>

            <textarea id="w3review" name="w3review" rows="4" cols="50">
            
            </textarea>
            <button type="submit" class="btn btn-primary">Kaydet</button>
            
        </form>
  
{% endblock slider %}