neos_kariyer/ads/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "ads"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addads/',views.addads,name = "add_ads"),
    path('adsupdate/<int:id>',views.updateads,name = "ads_update"),
    path('adsdelete/<int:id>',views.ads_delete,name = "ads_delete"),
    path('views/<int:id>',views.ads_views_offer,name = "ads_views_offer"),
]

neos_kariyer/neos_kariyer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from home.views import *
from all_category.views import mail_gonderme
urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include("user_operations.urls")),
    path('',home_index,name="index"),
    path('ads/',include("ads.urls")),
    path('profile/',include("profil.urls")),
    path('views/',include("offer.urls")),
    #path('buy/',include("pay.urls")),
    path('mail/',mail_gonderme,name = "mail"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

neos_kariyer/offer/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "adsoffer"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "offerdashboard"),
    path('adsshow/<int:id>',views.ads_show,name = "adsshow"),
    path('allads/',views.all_show_ads,name = "allads"),
    path('offerdelete/<int:id>',views.offer_delete,name = "offer_delete"),
    path('inbox/',views.expert_offer_views,name = "inbox"),
    path('allexpert/',views.expert_views_all,name = "allexpert"),
    path('delete/<int:id>',views.alinan_uzman_tekliflerini_sil,name = "alinan_uzman_tekliflerini_sil"),
    path('ilandavet/<int:id>/<int:users>',views.ilana_davet,name = "ilan_davet"),
    path('veto/<int:id>',views.alinan_uzman_tekliflerini_red,name = "alinan_uzman_tekliflerini_red"),
    path('onayla/<int:id>',views.alinan_uzman_tekliflerini_onayla,name = "alinan_uzman_tekliflerini_onayla"),
    path('deletet/<int:id>',views.aldigin_ilan_teklifleri_sil,name = "aldigin_ilan_teklifleri_sil"),
    path('vetot/<int:id>',views.aldigin_ilan_teklifleri_red,name = "aldigin_ilan_teklifleri_red"),
    path('onaylat/<int:id>',views.aldigin_ilan_teklifleri_onayla,name = "aldigin_ilan_teklifleri_onayla"),
]

neos_kariyer/user_operations/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user_operations"

urlpatterns = [
    path('register/',views.user_register,name = "register"),
    path('login/',views.user_login,name = "login"),
    path('logout/',views.user_logout,name = "logout"),
    path('reset/<int:idim>/<int:kod>',views.parola_sifirlama,name = "reset"),
    path('passrest/',views.pass_reset,name="passreset"),
    path('kod/',views.email_gonder,name = "email_gonder"),
    path('membership/<int:id>',views.membership,name = "membership"),

]

neos_kariyer/user_operations/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# kullanıcıların şirketmi yoksa freelancermi olduğunu belirler.
class user_status(models.Model):
    user = models.OneToOneField(User,null=True,on_delete = models.CASCADE,verbose_name="Kullanıcı Durumu")
    durum = models.BooleanField(null=True)

class parola_sifirla(models.Model):
    user = models.OneToOneField(User,null=True,on_delete = models.CASCADE,verbose_name="Kullanıcı Durumu")
    sifirla = models.IntegerField()

neos_kariyer/user_operations/forms.py
from django import forms
from django.forms import widgets

class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanıcı Adı" , widget=forms.TextInput(attrs={'placeholder': 'Kullanıcı Adı', 'class': 'form-control'}))
    password = forms.CharField(label = "Parola",widget = forms.PasswordInput(attrs={'placeholder': 'Parola', 'class': 'form-control'}))


class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50,label = "Kullanıcı Adı",widget=forms.TextInput(attrs={'class': "form-control", 
                'style': 'max-width: 600px;',
                'placeholder': 'Kullanıcı Adı'}))
    email = forms.EmailField(max_length=100,label = "Email",widget=forms.EmailInput(attrs={'class': "form-control", 
                'style': 'max-width: 600px;',
                'placeholder': 'E-Posta'}))
    password = forms.CharField(max_length=20,label = "Parola",widget = forms.PasswordInput(attrs={'class': "form-control", 
                'style': 'max-width: 600px;',
                'placeholder': 'Parola'}))
    confirm = forms.CharField(max_length=20,label ="Parolayı Doğrula",widget = forms.PasswordInput(attrs={'class': "form-control", 
                'style': 'max-width: 600px;',
                'placeholder': 'Parola Doğrula'}))
    
    def clean(self):
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm and len(password)<6:
            raise forms.ValidationError("Parola Hatalı")

        values = {
            "username" : username,
            "password" : password,
            "email"  : email
        }
        return values



class passreset(forms.Form):
    password = forms.CharField(max_length=20,label = "Parola",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="Parolayı Doğrula",widget = forms.PasswordInput)
    
    def clean(self):
        
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar Eşleşmiyor")

        values = {
            
            "password" : password
        }
        return values

neos_kariyer/user_operations/views.py
from django.shortcuts import render ,HttpResponse
from django.utils.datastructures import MultiValueDictKeyError
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from .models import *

# Create your views here.
#Kullanıcı Giriş Bölümü
def user_login(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            #messages.info(request,"Kullanıcı Adı veya Parola Hatalı")
            return render(request,"user_operations_temp/login.html",context)

        messages.success(request,"Başarıyla Giriş Yaptınız")
        login(request,user)
        #return redirect("index")
    return render(request, "user_operations_temp/login.html",context)
#Kullanını Kayıt Sayfasıdır.
def user_register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        newUser = User(username =username,email=email)
        newUser.set_password(password)
        try:
            newUser.save()
            login(request,newUser)
            messages.info(request,"Başarıyla Kayıt Oldunuz...")
            return redirect("/user/membership/3")
        except:
            messages.info(request,"İstediğiniz Kullanıcı Adı Kullanılmaktadır...")
            return redirect("/user/register/")
        
    context = {
            "form" : form
        }
    return render(request,"user_operations_temp/register.html",context)
def user_logout(request):
    logout(request)
    messages.success(request,"Başarıyla Çıkış Yaptınız")
    return redirect("index")
#Kullanıcı Druumlarını Düzenliyip Obje Oluşturulan Yerdir Bağlanti Models.py dir
def membership(request,id):
    if id == 3:
        print("Selamlar")
    elif id == 1:
        z  = user_status.objects.create(durum = 1)
        z.user = request.user
        z.save()
        return redirect("/profile/profil/")
    elif id == 0:
        z  = user_status.objects.create(durum = 0)
        z.user = request.user
        z.save()
        return redirect("/profile/company/")
    return render(request, "user_operations_temp/membership.html")
import random
from django.core.mail import send_mail
def email_gonder(request):
    print("Selam")
    username = request.POST.get('dili')
    mail_alindi = 0
    for i in username:
        if i == "@":
            mail_alindi = 1
            break
    if mail_alindi == 1:
        m = User.objects.filter(email=username)
        for i in m :
            idim = i.id
            mail = i.email
        try:
            ker = parola_sifirla.objects.filter(user_id = idim)
            
            print(ker)
        except:
            ker = 0
        if ker:
            gonder = random.randint(111111, 999999)
            print(gonder)
            parola_sifirla.objects.filter(user_id=idim).update(sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        else:
            gonder = random.randint(111111, 999999)
            parola_sifirla.objects.create(user_id=idim,sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        return redirect("/user/reset/")
    else:
        m = User.objects.filter(username=username)
        for i in m :
            idim = i.id
            mail = i.email
        try:
            ker = parola_sifirla.objects.filter(user_id = idim)
            
            print(ker)
        except:
            ker = 0
        if ker:
            gonder = random.randint(111111, 999999)
            print(gonder)
            parola_sifirla.objects.filter(user_id=idim).update(sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        else:
            gonder = random.randint(111111, 999999)
            parola_sifirla.objects.create(user_id=idim,sifirla = gonder)
            baslik = "Neos Kariyer Parola Sıfırlama"
            s =username+ """ Kullanıcısı 
            Parola Sıfırlma Kodu = """ +str(gonder)
            mail_adresi = mail
            send_mail(baslik,s,mail_adresi,[mail,mail_adresi])
        return redirect("/user/passrest/")
from .forms import passreset
def parola_sifirlama(request,idim,kod):
    form = passreset(request.POST or None)
    if form.is_valid():
        password = form.cleaned_data.get("password")
        user = User.objects.get(id=idim)
        print(idim)
        if parola_sifirla.objects.filter(user_id = idim,sifirla=kod):
            user.set_password(password)
            user.save()
            messages.success(request, "Parola Sıfırlandı")
            return redirect("/user/login/")
        else:
            messages.success(request, "Kullanıcı Bulunamadı")
            return redirect("/user/reset/")
    return render(request, "user_operations_temp/password_reset.html",{"form":form})

def pass_reset(request):
    if request.POST:
        users = request.POST.get("bilgi")
        print(users)
        kod = request.POST.get("dogrulaemail")
        print(kod)
        mail_alma = 0

        if users and kod :
            print("if 1")
            for i in users:
                if i == "@":
                    mail_alma = 1
                    print("if 2")
                    break
            if mail_alma:
                print("if 3")
                m = User.objects.filter(email=users)
                for i in m:
                    idim = i.id
                user = User.objects.get(id=idim)
                if parola_sifirla.objects.filter(user_id = idim,sifirla=kod):
                    print("kod Doğru",kod)
                    return redirect("/user/reset/"+str(idim)+"/"+str(kod))
                    
            else:
                print("if 3")
                m = User.objects.filter(username=users)
                for i in m:
                    idim = i.id
                user = User.objects.get(id=idim)
                if parola_sifirla.objects.filter(user_id = idim,sifirla=kod):
                    print("kod Doğru",kod)
                    return redirect("/user/reset/"+str(idim)+"/"+str(kod))
        else:   
            print("else 1")
    return render(request, "user_operations_temp/first_pass_reset.html")

neos_kariyer/user_operations/templates/footer.html
<div class="container-fluid pb-0 mb-0 justify-content-center text-light footer">
    <footer>
        <div class="row text-center py-5">

            <div class="row">
                <div class="col-md-3 col-6">
                    <h6 class="muted-text">
                        <b>YARDIM VE DESTEK</b>
                    </h6>
                    <small><a href="mailto:iletisim@yapbikariyer.com">iletisim@yapbikariyer.com</a></small>

                </div>
                <div class="col-md-3 col-6">
                    <h6 class="muted-text">
                        <b>MENÜ</b>
                    </h6>
                    <ul class="list-unstyled text-muted">
                        <li>Anasayfa</li>
                        <li>İlanlar</li>
                        <li>Uzmanlar</li>
                        <li>Hesabım</li>
                    </ul>
                </div>
                <div class="col-md-3 col-6">
                    <h6 class="muted-text">
                        <b>KURUMSAL</b>
                    </h6>
                    <ul class="list-unstyled text-muted">
                        <li>Hakkımızda</li>
                        <li>İletişim</li>
                        <li>Neos Yazılım</li>
                        <li>Instagram</li>
                    </ul>
                </div>
                <div class="col-md-3 col-6">
                    <h6 class="muted-text">
                        <b>GİZLİLİK VE KULLANIM</b>
                    </h6>
                    <ul class="list-unstyled text-muted">
                        <li>Üyelik sözleşmesi</li>
                        <li>Kullanım koşulları</li>
                        <li>KVKK</li>
                        <li>Aydınlatma metni</li>
                        <li>Mesafeli satış sözleşmesi</li>
                    </ul>
                </div>

            </div>
            <div class="row">
                <div class="col-12 text-center"><small class="rights">Neos Eğitim Bilişim Danışmanlık ve Ticaret
                        A.Ş<span>&#174;</span></small>
                    <br><small>Copyright <a href="https://neosyazilim.com/">@Neos Yazılım</a></small>
                </div>
            </div>
        </div>
    </footer>
</div>

neos_kariyer/user_operations/templates/head.html
{% load static%}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--Jquery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous" />

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <link rel="icon" type="image/x-icon" href="{% static 'images/logo.png' %}">

    <title>Neos Kariyer</title>

</head>

neos_kariyer/user_operations/templates/homebase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--Jquery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous" />

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <script src="https://kit.fontawesome.com/f57c714d8a.js" crossorigin="anonymous"></script>
    <title>Neos Kariyer</title>
    {% block head %}{% endblock %}
</head>

<body>

    {% block header %}{% endblock %}
    {% include "nav.html" %}
    {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}
                
                {% endif %}
    {% block slider %}{% endblock %}
               
    {% block content %}{% endblock %}
    <!--footer
    <?php include("includes/footer.php"); include("includes/scripts.php"); ?>-->
    <!--**footer**-->
    {% block footer %}{% endblock %}
    {% include "footer.html" %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>

neos_kariyer/user_operations/templates/ilan-filtre.html
<label for="kategori" class="form-label">Uzmanlık alanınız</label>
<select class="form-select" name="kategori" id="kategori">
    <option value="Tümü" selected>Tümü</option>
    {% for i in kategor %}
        <option value="{{i.kategory_ismi}}">{{i.kategory_ismi}}</option>
    {% endfor %}
</select>

<br>

<label for="lokasyon" class="form-label">Çalşmak istediğiniz lokasyon</label>
<select class="form-select" name="lokasyon" id="lokasyon">
    <option value="Tümü" >Tümü</option>
    {% for i in lokal %}
    {% if secim_sehir  ==  i.sehir_ismi %}
    {% else %}
    <option value="{{i.sehir_ismi}}">{{i.sehir_ismi}}</option>
    {% endif %}
    {% endfor %}
</select>

<br>
<label for="kategori" class="form-label">Aranan ilan tecrübesi</label>
<select class="form-select" name="deneyim" id="deneyimler">
    <option value="Tümü" >Tümü</option>
    {% for i in deneyimler %}
    {% if secim_deneyim == i.tecrube %}
    
    {% else %}
    <option value="{{i.tecrube}}">{{i.tecrube}}</option>
    {% endif %}
        
    {% endfor %}
</select>
<br>



<br>
<!--Eğer giriş/kayıt yapılmadıysa uyelik1.php sayfasına yönlendirir. Eğer giriş yapıldıysa kişiye uygun ilanlar gösterilir-->
<a href="uyelik1.php" title="Özgeçmişinize uygun ilanlar gösterilir"><small id="emailHelp"
        class="form-text text-muted">Bana uygun
        işleri göster</small></a>
<br><br>
<button type="submit"  class="btn w-100" style="background-color:#d5d6de;"><b>ARA</b></button>

neos_kariyer/user_operations/templates/nav.html
{% load static %}

<nav class="navbar-desktop navbar navbar-expand-sm navbar-light bg-light py-3">
    <div class="container">
        <a class="navbar-brand" href="/"><img src="{% static 'images/logo.png' %}" alt="yapbikariyer logo" width="60"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Anasayfa</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'adsoffer:allads' %}">İlanlar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'adsoffer:allexpert' %}">Uzmanlar</a>
                </li>

            </ul>
            <form class="d-flex">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    
                    {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link active dropdown-toggle" href="/profile/profil/" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Hesabım
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/profile/profil/">Profil</a></li>
                            <li><a class="dropdown-item" href="{% url 'adsoffer:offerdashboard'  %}">Başvurularım</a></li>
                            {% if ilan_yapma %}
                            
                            {% else %}
                            <li><a class="dropdown-item" href="/ads/dashboard/">İlanlarım</a></li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{% url 'adsoffer:inbox'  %}">Gelen kutusu</a></li>
                            <li><a class="dropdown-item" href="/profile/favorilerim/">İzleme Listem</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/buy/buy/">Bakiye: {{bakiye}}ƒ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#"><img class="rounded-circle" src="{% static '/images/ilan-avatar.png' %}" alt="" style="width:35px;height:35px;object-fit:cover;"></a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link active " style="color: grey !important;"  aria-current="page" href="{% url 'user_operations:logout'  %}">Çıkış</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        
                        <a class="nav-link active " style="color: green !important;" aria-current="page" href="{% url 'user_operations:login'  %}">Giriş</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active " style="color: green !important;"  aria-current="page" href="{% url 'user_operations:register'  %}">Kaydol</a>
                    </li>
                    {% endif %}
                    
                </ul>
            </form>
        </div>
    </div>
</nav>

<!--**navbar for desktop**-->

neos_kariyer/user_operations/templates/panel.html
<h3>Profil</h3>
<h3>İlanlarım</h3>
<h3>Devam Eden</h3>
<h3>İzleme Listem</h3>
<h3>Bildirimler</h3>

neos_kariyer/user_operations/templates/scripts.html
<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous">
</script>
<script>
if ($(window).width() < 960) {
    $(".mainnav").removeClass("fixed-top")
}
$("#uyeOpen").click(function() {
    $(".hero-image-short").slideUp(function() {
        $("#full-width").slideDown()
    })

})
//profil-duzenle
$("#profileImage").click(function(e) {
    $("#imageUpload").click();
});
$("#yetenekEkle").click(function(e) {
    yetenekInputu = $(".yeniYetenek").html()
    $('#yetenekEkle').before(yetenekInputu);

});
</script>

neos_kariyer/user_operations/templates/uzman-filtre.html
<label for="kategori" class="form-label">Aradığınız uzmanlık</label>
<select class="form-select" name="kategori" id="kategori">
    <option value="Tümü" >Tümü</option>
        <option value="{{secim_kategori}}" selected>{{secim_kategori}}</option>

    {% for i in kategori %}
    {% if i.kategory_ismi == secim_kategori %}
    
    {% else %}
        <option value="{{i.kategory_ismi}}">{{i.kategory_ismi}}</option>
    {% endif %}
        
    {% endfor %}
</select>

<br>

<label for="kategori" class="form-label">Lokasyon</label>
<select class="form-select" name="lokasyon" id="kategori">
    <option value="Tümü" >Tümü</option>
    <option value="{{secim_sehir}}" selected>{{secim_sehir}}</option>
    {% for i in lokal %}
    {% if secim_sehir  ==  i.sehir_ismi %}
    
    {% else %}
    <option value="{{i.sehir_ismi}}">{{i.sehir_ismi}}</option>
    {% endif %}
        
    {% endfor %}
</select>

<br>

<label class="form-label">Uzmanın deneyim seviyesi</label><br>

<select class="form-select" name="deneyim" id="deneyimler">
    <option value="Tümü" >Tümü</option>
    <option value="{{secim_deneyim}}" selected>{{secim_deneyim}}</option>
    {% for i in deneyimler %}
    {% if secim_deneyim == i.tecrube %}
    
    {% else %}
    <option value="{{i.tecrube}}">{{i.tecrube}}</option>
    {% endif %}
        
    {% endfor %}
</select>

<br>


<!--Eğer giriş/kayıt yapılmadıysa uyelik1.php sayfasına yönlendirir. Eğer giriş yapıldıysa kişiye uygun ilanlar gösterilir-->
<a href="/views/allexpert/" title="İlan yayınlarsanız uzmanlar sizi bulur"><small id="emailHelp"
        class="form-text text-muted">İlan yayınla</small></a>
<br><a href="" title="İlan yayınlarsanız uzmanlar sizi bulur"><small id="emailHelp"
    class="form-text text-muted">Filtreyi Sıfırla</small></a><br>
    <button class="btn btn-success w-100" type="submit">ARA</button>